### PR TITLE
Create dev and staging DNS resources for VINCE-NT application

### PR DESCRIPTION
**Pull request by jmorrowomni**
#  #

## 🗣 Description ##

Add DNS entries for the development and staging environments for VINCE-NT.

## 💭 Motivation and context ##

VINCE-NT (Vulnerablity Information and Coordination Enviornment -
New Technology) is an application being moved over to CISA, which was
formerly hosted by Analygence.  DNS entries are required to access the
development and staging platforms being hosted in Mission Engineering's
Landing Zone.

## 🧪 Testing ##

After the DNS records are created, a tool like dig will be used to verify
the records.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
@jmorrowomni - Can you fix the failing linter or do you want me to do that?

**Comment by jmorrowomni** [comment]
> @jmorrowomni - Can you fix the failing linter or do you want me to do that?

I can take care of it

**Comment by jsf9k** [comment]
@jmorrowomni - I applied these changes.  Can you verify that things work as expected?

**Comment by jmorrowomni** [comment]
@jsf9k - I messed up the staging DNS entry, repushing now.  The dev entry was working properly, however

image

**Review by dav3r — APPROVED** [review]
LGTM

**Comment by jsf9k** [comment]
@jmorrowomni - OK, I reapplied.  Please do your check again.

**Review by jsf9k — APPROVED** [review]

**Comment by jmorrowomni** [comment]
@jsf9k - Now it looks good!  Thank you 👍 

image

**Pull request merged**
