### PR TITLE
update vincent dev hostname to point to cloudfront

### PR DESCRIPTION
**Pull request by jwoytek-cisa**
#  #

## 🗣 Description ##

These changes are to point the existing FQDN for VINCE-NT DEV at the test Cloudfront distribution for connectivity testing.

## 💭 Motivation and context ##

This is to support testing Cloudfront and preparing to move VINCE-NT to staging for the next steps in deployment.

## 🧪 Testing ##

Cloudfront distribution FQDN has been verified.

## ✅ Pre-approval checklist ##

- [X] This PR has an informative and human-readable title.
- [X] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [X] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [X] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).

### CODE REVIEW

**Comment by jsf9k** [comment]
@jwoytek-cisa - I have applied your change.  Please test and let me know if things seem to be working as expected.

**Comment by jsf9k** [comment]
I also rebased your commit onto the latest from upstream `develop`.  You were 150+ commits behind.

**Comment by jwoytek-cisa** [comment]
Looks good! Thank you! And apologies for the rebase issue--my fork was out of date but I missed it when I was making this update.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍

**Comment by jsf9k** [comment]
@jwoytek-cisa - Now that you have two approving reviews your PR should merge automatically once the checks are able to run.  I'll keep an eye on it and reach out if there are any issues.

**Comment by jwoytek-cisa** [comment]
Thank you!

**Pull request merged**
