### PR TITLE
Update Crossfeed DNS entries to enable certificate verification

### PR DESCRIPTION
**Pull request by aloftus23**
#  #

## 🗣 Description ##

Need to remove the existing connection to the staging-cd and api.staging-cd certs, so that we can create new ones. 

- [x] Apply terraform without the CNAME route53 records
- [x] Remove the Certificates in the Crossfeed AWS account
- [x] Create new certificates in the Crossfeed AWS account
- [ ] Re-add CNAME route53 records and run terraform

## 💭 Motivation and context ##

Crossfeed needs to create new certificates because the existing one's have expired. ACM isn't allowing us to create new certificates without removing the old expired ones.

The problem is the expired Crossfeed certificates cannot be removed because they are still connected to the load balancers in this AWS configuration. 

So we can run the terraform to disconnect them, then create the new certs, and then re-add the CNAMEs.

## 🧪 Testing ##

Terrafrom plan and apply

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [ ] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

## ✅ Pre-merge checklist ##

- [ ] Re-run `terraform-docs` if anything relevant changes.

### CODE REVIEW

**Comment by dav3r** [comment]
@aloftus23 I applied your changes and those two CNAME records have been removed.  When you update this PR with the new certificate validation info, I will re-apply.

**Comment by dav3r** [comment]
Adding `blocked` tag until @aloftus23 updates this PR with the new certificate validation info.

**Comment by aloftus23** [comment]
@dav3r Ok we ran through the steps, so should be ready to re-apply the uncommented resources. The CNAME record and value of the new certificates are the same so this PR can simply be closed if it works.

**Comment by dav3r** [comment]
OK, I reapplied the Terraform.  If everything is working from your end, please let us know and I can simply close out this PR.

**Comment by aloftus23** [comment]
> OK, I reapplied the Terraform. If everything is working from your end, please let us know and I can simply close out this PR.

@dav3r Didn't work for some reason. Do you mind running again and seeing if there's any errors this time?

**Comment by dav3r** [comment]
> > OK, I reapplied the Terraform. If everything is working from your end, please let us know and I can simply close out this PR.
> 
> @dav3r Didn't work for some reason. Do you mind running again and seeing if there's any errors this time?

@aloftus23 There are no changes to re-apply in the Terraform.  Are you sure that the new certificates have the same validation info?  I was expecting that to change here:
https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/cd20047d480ccbf302e014a90418ed697b572b44/route53_crossfeed_app.tf#L269
and here:
https://github.com/cisagov/cool-dns-cyber.dhs.gov/blob/cd20047d480ccbf302e014a90418ed697b572b44/route53_crossfeed_app.tf#L373

**Comment by aloftus23** [comment]
This is PR is no longer needed and being addressed in #104 and #103

**Pull request closed without merging**
