### PR TITLE
Add entries to support PIV for RSAA

### PR DESCRIPTION
**Pull request by jmorrowomni**
#  #

## 🗣 Description ##

Add a staging and development CNAME entry to support PIV authentication for RSAA.

## 💭 Motivation and context ##

In order to support PIV passthrough, a new domain and function are required.  
These entries are for RSAA to be able to pass PIV information to the Okta backend.

## 🧪 Testing ##

Name resolution will be tested using dig or similar tools.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated
      to reflect the changes in this PR.
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by jsf9k** [comment]
@jmorrowomni - I applied these changes to production, so you can go ahead and verify functionality while we review.

**Review by jsf9k — CHANGES_REQUESTED** [review]
Please update the `terraform-docs` output in `README.md`.

**Comment by jmorrowomni** [comment]
> Please update the `terraform-docs` output in `README.md`.

@jsf9k Please see 6d94b252a38d171a28683a805976675c67571f14

**Comment by jmorrowomni** [comment]
> @jmorrowomni - I applied these changes to production, so you can go ahead and verify functionality while we review.

@dav3r Testing looks good, thanks!

**Comment by jsf9k** [comment]
> > @jmorrowomni - I applied these changes to production, so you can go ahead and verify functionality while we review.
> 
> @dav3r Testing looks good, thanks!

It was me who applied the changes so you could test, not @dav3r. :cry:

**Comment by jmorrowomni** [comment]
image
image

**Review by jsf9k — APPROVED** [review]

**Comment by jmorrowomni** [comment]
> > > @jmorrowomni - I applied these changes to production, so you can go ahead and verify functionality while we review.
> > 
> > 
> > @dav3r Testing looks good, thanks!
> 
> It was me who applied the changes so you could test, not @dav3r. 😢

I saw that Dave liked your comment so he was the last name in my mind!  You know I <3 you @jsf9k

**Review by dav3r — APPROVED** [review]
👍 👍

**Pull request merged**
