### PR TITLE
Add crossfeed prod DNS entries for LZ

### PR DESCRIPTION
**Pull request by epicfaace**
- Add crossfeed prod DNS entries for LZ
- Replace SES DNS entries for Crossfeed prod LZ, so we can verify the domain on the LZ account
- Add SES DNS entries for Crossfeed staging LZ, so we can verify the domain on the LZ account
- Remove old SES entries for the COOL (where Crossfeed is no longer deployed)

### CODE REVIEW

**Comment by jsf9k** [comment]
@epicfaace - I'd like to test these changes by going ahead and applying them from the PR branch.  (Because I don't want to repeat the cataclysm that was #76 and #78.)  Is that OK to do here?

**Comment by epicfaace** [comment]
> Is that OK to do here?

Yes, please do! Thanks.

**Comment by jsf9k** [comment]
> > Is that OK to do here?
> 
> Yes, please do! Thanks.

OK, the changes have been applied and the apply was successful.  Can you let us know if things seem correct?

**Comment by epicfaace** [comment]
@jsf9k I forgot to change the API entries; just updated. Can you please re-deploy when you get a chance so we can test?

Thanks!

**Comment by jsf9k** [comment]
> @jsf9k I forgot to change the API entries; just updated. Can you please re-deploy when you get a chance so we can test?
> 
> Thanks!

The new changes have been applied.

**Review by jsf9k — APPROVED** [review]

**Review by dav3r — APPROVED** [review]
👍 👍

**Comment by jsf9k** [comment]
@epicfaace - Let me know how the testing goes.  If it's successful then I'll merge this PR.

**Comment by jsf9k** [comment]
> @epicfaace - Let me know how the testing goes. If it's successful then I'll merge this PR.

@epicfaace - How did your testing go?

**Comment by epicfaace** [comment]
Still working on it. We're working with a team to deploy the right certs so the site goes up, should know later this week. (cc @stewartl97 @aloftus23 )

**Comment by jsf9k** [comment]
> Still working on it. We're working with a team to deploy the right certs so the site goes up, should know later this week. (cc @stewartl97 @aloftus23 )

Any progress on testing?

**Comment by epicfaace** [comment]
> > Still working on it. We're working with a team to deploy the right certs so the site goes up, should know later this week. (cc @stewartl97 @aloftus23 )
> 
> Any progress on testing?

Yes, it all works now! So we should be good to merge.

There might potentially be some issues with SES verification on the new AWS account (@aloftus23 would know more) -- if so we will follow up with an additional PR to fix that.

**Comment by jsf9k** [comment]
@epicfaace - I can't push to this branch.  That's a problem because I need to rebase onto our `develop` before I can merge.  Can you give me permission to push?  I think there is something you can click on in your PR to allow this, since your PR was created from a fork.

**Comment by epicfaace** [comment]
Try again -- just gave you access

**Comment by jsf9k** [comment]
> Try again -- just gave you access

Thank you!

**Pull request merged**
